### PR TITLE
Remove use of 'static in select.rs

### LINKED ISSUE #14: Using chan_select! requires values to be 'static
Using `chan_select!` forces values to be static for no apparent reason.  At the time of writing, here: https://github.com/BurntSushi/chan/blob/12919f83a8990ed391c6a0c334d04e2184410e5a/src/select.rs#L239

This is very inconvenient while using a scoped thread pool where threads communicate with each other via pointers into a big buffer. All of the normal channel operations work fine, except `chan_select!`

### PR DESCRIPTION
**Pull request by dflemstr**
Fixes #14

### CODE REVIEW

**Comment by BurntSushi** [comment]
Could you add `Fixes #14` to the commit message so they are linked? Otherwise, this looks good, thank you!

**Comment by dflemstr** [comment]
Don't have a computer for the rest of the day, will update commit message later!  Maybe the PR description is enough?

**Comment by meh** [comment]
@BurntSushi any update on this?

**Comment by BurntSushi** [comment]
@meh Thanks for the ping! @dflemstr Thanks for the PR!

**Comment by BurntSushi** [comment]
This PR is in `chan 0.1.19` on crates.io.

**Pull request merged**
